name = "trastocker"
send_metrics = false

compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "trastocker"
database_id = "f33035ec-c9be-47bb-bff8-d182b3b722bf"

[env.dev]
[[env.dev.d1_databases]]
binding = "DB"
database_name = "trastocker"
database_id = "f33035ec-c9be-47bb-bff8-d182b3b722bf"

[env.dev.vars]
APP_ENV = "local"
NODE_ENV = "development"
APP_DOMAIN = "localhost"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "trastocker"
database_id = "f33035ec-c9be-47bb-bff8-d182b3b722bf"

[env.production.vars]
APP_ENV = "production"
NODE_ENV = "production"
