export const INJECT_KEY = {
  UserLoginUseCase: Symbol.for('UserLoginUseCase'),
  GetAuthUserUseCase: Symbol.for('GetAuthUserUseCase'),
  CreateUserUseCase: Symbol.for('CreateUserUseCase'),
  CreateWorkspaceByNameService: Symbol.for('CreateWorkspaceByNameService'),
  AssignWorkspaceByInviteCodeService: Symbol.for('AssignWorkspaceByInviteCodeService'),
  AssignWorkspaceByIdService: Symbol.for('AssignWorkspaceByIdService'),
  CanCreateUserService: Symbol.for('CanCreateUserService'),
  CreateUserService: Symbol.for('CreateUserService'),
  GetUserJoinedWorkspacesService: Symbol.for('GetUserJoinedWorkspacesService'),
  GetWorkspaceJoinedUsersService: Symbol.for('GetWorkspaceJoinedUsersService'),
  UserRepository: Symbol.for('UserRepository'),
  UserTokenRepository: Symbol.for('UserTokenRepository'),
  WorkspaceRepository: Symbol.for('WorkspaceRepository'),
  WorkspaceUserRepository: Symbol.for('WorkspaceUserRepository'),
  EmailNotification: Symbol.for('EmailNotification'),
  D1Database: Symbol.for('D1Database'),
  Resend: Symbol.for('Resend'),
};
