name: Build test

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup/pnpm

      # TODO: We need to make adjustments to allow Build to come through.
      # - name: Build packages
      #   run: pnpm run build
