name: Delete Visual Regression test result report

on:
  pull_request:
    types:
      - closed

jobs:
  delete-vrt-result-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS CLI for Cloudflare R2
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CLOUDFLARE_R2_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CLOUDFLARE_R2_S3_SECRET_KEY_ID }}
          aws-region: auto

      - name: Delete VRT result report for all PR commits
        env:
          BUCKET_NAME: storybook-visual-regression-test-result
          R2_ENDPOINT: https://3f29f61c3f8823d6a2c127330be6766d.r2.cloudflarestorage.com
        run: |
          commit_hashes=$(git log --pretty=format:"%H" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          for commit_hash in ${commit_hashes}
          do
            echo "Processing commit: $commit_hash"
            if aws s3 ls "s3://${BUCKET_NAME}/${commit_hash}/" --endpoint-url=$R2_ENDPOINT; then
              aws s3 rm "s3://${BUCKET_NAME}/${commit_hash}/" --recursive --endpoint-url=$R2_ENDPOINT
              echo "Deleted VRT result report for commit ${commit_hash}"
            else
              echo "No VRT result report found for commit ${commit_hash}"
            fi
          done
