name: Deploy Storybook

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup/pnpm

      - name: Build Storybook
        run: pnpm run storybook:build
        working-directory: apps/app-frontend-server

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/apps/app-frontend-server/storybook-static

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
