name: Deploy GitHub Pages

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup/pnpm

      - name: Build packages
        run: pnpm run build:libraries

      - name: Build app-preview-server
        run: pnpm run build
        working-directory: apps/app-preview-server

      - name: Build ui-elements Storybook
        run: pnpm run storybook:build
        working-directory: libraries/ui-elements

      - name: Generate mock database for storybook
        run: pnpm run generate:mock-database
        working-directory: apps/app-frontend-server

      - name: Move ui-elements Storybook Dist
        run: |
          mkdir apps/app-preview-server/dist/storybook/ui-elements
          cp -r libraries/ui-elements/storybook-static/* apps/app-preview-server/dist/storybook/ui-elements

      - name: Build app-frontend-server Storybook
        run: pnpm run storybook:build
        working-directory: apps/app-frontend-server

      - name: Move app-frontend-server Storybook Dist
        run: |
          mkdir apps/app-preview-server/dist/storybook/app-frontend-server
          cp -r apps/app-frontend-server/storybook-static/* apps/app-preview-server/dist/storybook/app-frontend-server

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/apps/app-preview-server/dist

  deploy:
    needs: build
    runs-on: ubuntu-24.04-arm
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
