name: Lint test

on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-24.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup/pnpm

      - name: Setup ESLint cache
        uses: actions/cache@v4
        with:
          path: |
            apps/app-backend-server/.eslintcache
            apps/app-frontend-server/.eslintcache
            definitions/database-definition/.eslintcache
            definitions/graphql-definition/.eslintcache
            definitions/validation-schema-definition/.eslintcache
            middlewares/reverse-proxy-middleware/.eslintcache
          key: ${{ runner.os }}-eslint-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-eslint-cache-

      - name: Build packages
        run: pnpm run build:definition

      - name: Lint Code
        run: pnpm run lint:code
