name: Visual Regression test

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup/pnpm

      - name: Build packages
        run: pnpm run build:definition

      - name: Build Storybook
        run: pnpm run storybook:build
        working-directory: apps/app-frontend-server

      - name: Screenshot Stories
        run: pnpm run storybook:screenshot
        working-directory: apps/app-frontend-server

      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull

      - name: Report Visual Regression test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_S3_SECRET_KEY_ID }}
        run: pnpm reg-suit run
        working-directory: apps/app-frontend-server
